name: drag_list
description: Flutter list widget that allows to drag and drop items as well as define custom drag handle widget.
version: 1.0.1
author: Tomasz Wyrowinski <tomwyr@hotmail.com>
homepage: https://github.com/tomwyr/drag-list/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
